from pathlib import Path

BASE = Path(".")
DOMAINS_DIR = BASE / "domains"
OUT = BASE / "generated" / "dns-auto2.rsc"

# Файлы, которые НЕ надо обрабатывать как обычные списки доменов.
# regex.txt имеет отдельный формат: comment|address-list|pattern
SKIP_FILES = {"regex.txt"}
REGEX_FILE = DOMAINS_DIR / "regex.txt"


def read_lines(path: Path):
    if not path.exists():
        return []

    result = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip().lower()
        if not line or line.startswith("#"):
            continue
        result.append(line)

    return sorted(set(result))


def address_list_from_file(path: Path) -> str:
    """gpt.txt -> to_mihomo_gpt, social.txt -> to_mihomo_social"""
    return f"to_mihomo_{path.stem.lower()}"


def comment_from_file(path: Path) -> str:
    """gpt.txt -> github:gpt, social.txt -> github:social"""
    return f"github:{path.stem.lower()}"


def build_normal_group(path: Path):
    domains = read_lines(path)
    comment = comment_from_file(path)
    address_list = address_list_from_file(path)

    lines = [f'/ip dns static remove [find where comment="{comment}"]']

    for domain in domains:
        lines.append(
            f'/ip dns static add name={domain} type=FWD match-subdomain=yes '
            f'address-list={address_list} comment="{comment}"'
        )

    lines.append("")
    return lines


def build_regex_group():
    lines = []
    if not REGEX_FILE.exists():
        return lines

    regex_entries = []
    for raw in REGEX_FILE.read_text(encoding="utf-8").splitlines():
        raw = raw.strip()
        if not raw or raw.startswith("#"):
            continue

        parts = raw.split("|", 2)
        if len(parts) != 3:
            continue

        comment, address_list, pattern = parts
        regex_entries.append((comment.strip(), address_list.strip(), pattern.strip()))

    comments = sorted(set(entry[0] for entry in regex_entries))
    for comment in comments:
        lines.append(f'/ip dns static remove [find where comment="{comment}"]')

    for comment, address_list, pattern in regex_entries:
        safe_pattern = pattern.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(
            f'/ip dns static add regexp="{safe_pattern}" type=FWD '
            f'address-list={address_list} comment="{comment}"'
        )

    if regex_entries:
        lines.append("")

    return lines


def find_domain_files():
    if not DOMAINS_DIR.exists():
        return []

    return sorted(
        path for path in DOMAINS_DIR.glob("*.txt")
        if path.name.lower() not in SKIP_FILES
    )


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# auto-generated by generate_dns2.py",
        "",
    ]

    domain_files = find_domain_files()
    for path in domain_files:
        lines.extend(build_normal_group(path))

    lines.extend(build_regex_group())

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Generated {OUT}")
    print(f"Processed domain files: {len(domain_files)}")
    for path in domain_files:
        print(f"- {path.name} -> {address_list_from_file(path)}")


if __name__ == "__main__":
    main()
