from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
DOMAINS_DIR = BASE_DIR / "domains"
OUTPUT_DIR = BASE_DIR / "generated"
OUTPUT_FILE = OUTPUT_DIR / "dns-auto.rsc"

GROUPS = [
    {"file": "gpt.txt", "comment": "github:gpt", "address_list": "to-mihomo"},
    {"file": "youtube.txt", "comment": "github:youtube", "address_list": "to-mihomo"},
]

def read_domains(path: Path) -> list[str]:
    if not path.exists():
        return []
    result = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        result.append(line.lower())
    return sorted(set(result))

def build_group(group: dict) -> list[str]:
    domains = read_domains(DOMAINS_DIR / group["file"])
    comment = group["comment"]
    address_list = group["address_list"]

    lines = []
    lines.append(f'/ip dns static remove [find where comment="{comment}"]')

    for domain in domains:
        lines.append(
            f'add name={domain} type=FWD match-subdomain=yes '
            f'address-list={address_list} comment="{comment}"'
        )
    lines.append("")
    return lines

def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    lines = [
        "# This file is auto-generated by GitHub Actions",
        "/ip dns static",
        "",
    ]

    for group in GROUPS:
        lines.extend(build_group(group))

    OUTPUT_FILE.write_text("\n".join(lines).strip() + "\n", encoding="utf-8")
    print(f"Generated: {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
