from __future__ import annotations

import argparse
import ipaddress
import json
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOMAINS_DIR = ROOT / "domains"
NETWORKS_DIR = ROOT / "networks"
UPSTREAM_DIR = ROOT / "upstream"
SOURCES_FILE = ROOT / "sources.json"
OUTPUT_FILE = ROOT / "generated" / "dns-auto.rsc"
RAW_V2FLY = "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/{name}"
LIST_PREFIX = "to-vpn"
DOMAIN_RE = re.compile(r"^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")


def read_values(path: Path) -> set[str]:
    if not path.exists():
        return set()
    values: set[str] = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        value = raw.split("#", 1)[0].strip().lower()
        if value:
            values.add(value)
    return values


def validate_group(group: str) -> None:
    if not re.fullmatch(r"[a-z0-9][a-z0-9_-]*", group):
        raise ValueError(f"Invalid group name: {group}")


def normalize_domain(value: str) -> str | None:
    value = value.strip().lower().rstrip(".")
    for prefix in ("domain:", "full:"):
        if value.startswith(prefix):
            value = value[len(prefix):]
            break
    if value.startswith(("regexp:", "keyword:")):
        return None
    value = value.split()[0]
    return value if DOMAIN_RE.fullmatch(value) else None


def fetch_v2fly_list(name: str, cache: dict[str, set[str]]) -> set[str]:
    if name in cache:
        return cache[name]
    request = urllib.request.Request(
        RAW_V2FLY.format(name=name), headers={"User-Agent": "dns-files-builder/1"}
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        text = response.read().decode("utf-8")
    domains: set[str] = set()
    includes: list[str] = []
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if line.startswith("include:"):
            includes.append(line.split()[0].split(":", 1)[1])
            continue
        domain = normalize_domain(line)
        if domain:
            domains.add(domain)
    cache[name] = domains
    for include in includes:
        domains.update(fetch_v2fly_list(include, cache))
    return domains


def update_upstream(sources: dict[str, list[str]]) -> None:
    UPSTREAM_DIR.mkdir(parents=True, exist_ok=True)
    cache: dict[str, set[str]] = {}
    for group, source_names in sorted(sources.items()):
        validate_group(group)
        domains: set[str] = set()
        for source_name in source_names:
            domains.update(fetch_v2fly_list(source_name, cache))
        (UPSTREAM_DIR / f"{group}.txt").write_text(
            "\n".join(sorted(domains)) + "\n", encoding="utf-8"
        )
        print(f"Updated upstream/{group}.txt: {len(domains)} domains")


def load_domain_groups(sources: dict[str, list[str]]) -> dict[str, set[str]]:
    groups: dict[str, set[str]] = {}
    names = set(sources) | {path.stem for path in DOMAINS_DIR.glob("*.txt")}
    for group in sorted(names):
        validate_group(group)
        domains = read_values(DOMAINS_DIR / f"{group}.txt")
        domains.update(read_values(UPSTREAM_DIR / f"{group}.txt"))
        invalid = sorted(value for value in domains if not DOMAIN_RE.fullmatch(value))
        if invalid:
            raise ValueError(f"Invalid domains in {group}: {invalid[:5]}")
        if not domains:
            raise ValueError(f"Domain group is empty: {group}")
        groups[group] = domains
    return groups


def normalize_network(value: str, source: Path) -> str:
    try:
        network = ipaddress.ip_network(value, strict=False)
    except ValueError as error:
        raise ValueError(f"Invalid network in {source}: {value}") from error
    if network.version != 4:
        raise ValueError(f"IPv6 is not supported in {source}: {value}")
    if network.is_private or network.is_loopback or network.is_link_local:
        raise ValueError(f"Private/reserved network is forbidden in {source}: {value}")
    if network.prefixlen < 16:
        raise ValueError(f"Network is too broad in {source}: {value}")
    return str(network.network_address) if network.prefixlen == 32 else str(network)


def load_network_groups() -> dict[str, set[str]]:
    groups: dict[str, set[str]] = {}
    for path in sorted(NETWORKS_DIR.glob("*.txt")):
        validate_group(path.stem)
        values = {normalize_network(value, path) for value in read_values(path)}
        if values:
            groups[path.stem] = values
    return groups


def render(groups: dict[str, set[str]], networks: dict[str, set[str]]) -> str:
    lines = [
        "# dns-files generated-v2; do not edit manually",
        f"# domain-groups={len(groups)} network-groups={len(networks)}",
        "",
        "# Remove entries generated by the legacy repository format.",
        '/ip dns static remove [find where comment~"^github:"]',
        '/ip firewall address-list remove [find where comment~"^github:network:"]',
        "",
    ]
    for group, domains in sorted(groups.items()):
        comment = f"github:dns-files:{group}"
        address_list = f"{LIST_PREFIX}-{group}"
        lines.extend([
            f"# group={group} domains={len(domains)}",
            f'/ip dns static remove [find where comment="{comment}"]',
        ])
        for domain in sorted(domains):
            lines.append(
                f'/ip dns static add name="{domain}" type=FWD match-subdomain=yes '
                f'address-list={address_list} comment="{comment}"'
            )
        lines.append("")
    for group, values in sorted(networks.items()):
        comment = f"github:dns-files:network:{group}"
        address_list = f"{LIST_PREFIX}-{group}"
        lines.extend([
            f"# network-group={group} entries={len(values)}",
            f'/ip firewall address-list remove [find where comment="{comment}"]',
        ])
        for value in sorted(values):
            lines.append(
                f'/ip firewall address-list add list={address_list} address={value} '
                f'comment="{comment}"'
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--update-upstream", action="store_true")
    args = parser.parse_args()
    sources = json.loads(SOURCES_FILE.read_text(encoding="utf-8"))
    if args.update_upstream:
        update_upstream(sources)
    groups = load_domain_groups(sources)
    networks = load_network_groups()
    output = render(groups, networks)
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(output, encoding="utf-8")
    print(f"Generated {OUTPUT_FILE}: {len(output)} bytes")


if __name__ == "__main__":
    main()
